lib/app_web/router.ex
defmodule AppWeb.Router do
  use AppWeb, :router

  import AppWeb.UserAuth
  import AppWeb.SessionHelpers

  # Strange behaviour, require forces the compiler to process now
  # https://github.com/elixir-cldr/cldr/issues/135
  require App.Cldr

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug RemoteIp
    plug :assign_remote_ip
    plug Cldr.Plug.AcceptLanguage, cldr_backend: App.Cldr
    plug Cldr.Plug.SetLocale, apps: [:cldr, :gettext], cldr: App.Cldr, gettext: AppWeb.Gettext
    plug :assign_cldr_locale
    plug :fetch_live_flash
    plug :put_root_layout, {AppWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug RemoteIp
    plug :assign_remote_ip
  end

  scope "/", AppWeb do
    pipe_through :browser

    # live "/", PageLive, :index
    get "/", HomeController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", AppWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test, :prod] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through [:browser, :require_authenticated_user]
      live_dashboard "/dashboard", metrics: AppWeb.Telemetry, ecto_repos: [App.Repo]
    end
  end

  ## Authentication routes

  scope "/", AppWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    live "/users/register", RegisterLive, :new, as: :user_registration
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", AppWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", AppWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm
  end

  scope "/stripe/webhooks" do
    post "/", WebhooksController, :webhooks
  end

  scope "/threejs/", AppWeb do
    pipe_through [:browser]

    get "/", ThreeJSController, :index
    get "/fancy_cube", ThreeJSController, :fancy_cube
    get "/:id", ThreeJSController, :scene
  end

  scope "/api", AppWeb do
    pipe_through [:api]

    post "/session/set-timezone", SessionSetTimezoneController, :set
  end
end

lib/app_web/views/layout_view.ex
defmodule AppWeb.LayoutView do
  use AppWeb, :view
end

lib/app_web/templates/layout/_user_menu.html.eex
<%= if @current_user do %>
  <li><%= link @current_user.email, to: Routes.user_settings_path(@conn, :edit), title: "Settings" %></li>
  <li><%= link "Log out", to: Routes.user_session_path(@conn, :delete), method: :delete %></li>
<% else %>
  <li><%= link "Register", to: Routes.user_registration_path(@conn, :new) %></li>
  <li><%= link "Log in", to: Routes.user_session_path(@conn, :new) %></li>
<% end %>

lib/app_web/templates/layout/app.html.eex
<main role="main" class="container">
  <%= if get_flash(@conn, :info) do %>
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <% end %>
  <%= if get_flash(@conn, :error) do %>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <% end %>
  <%= @inner_content %>
</main>

lib/app_web/templates/layout/live.html.leex
<main role="main" class="container">
  <%= if @live_action do%>
  <%= if live_flash(@flash, :info) do %>
    <p class="alert alert-info" role="alert"
      phx-click="lv:clear-flash"
      phx-value-key="info"><%= live_flash(@flash, :info) %></p>
  <% end %>
  <%= if live_flash(@flash, :error) do %>
    <p class="alert alert-danger" role="alert"
      phx-click="lv:clear-flash"
      phx-value-key="error"><%= live_flash(@flash, :error) %></p>
  <% end %>
  <% end %>
  <%= @inner_content %>
</main>

lib/app_web/templates/layout/root.html.leex
<!DOCTYPE html>
<html lang="<%= @locale.language %>">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "App", suffix: " · UDIA" %>
    <link phx-track-static rel="stylesheet" href="<%= Routes.static_path(@conn, "/app.css") %>" media="all"/>
    <script defer phx-track-static type="text/javascript" src="<%= Routes.static_path(@conn, "/app.js") %>"></script>
  </head>
  <body>
    <script>true;// FOUC https://bugzilla.mozilla.org/show_bug.cgi?id=1404468</script>
    <canvas id="canvas"></canvas>
    <div id="wrapper">
      <header id="header">
        <section class="container">
          <a id="logo-link" href="<%= Routes.home_path(@conn, :index) %>">
            <object id="logo" class="udia-logo" aria-label="UDIA" type="image/svg+xml" data="<%= Routes.static_path(@conn, "/images/logo.svg") %>">
              <img src="<%= Routes.static_path(@conn, "/images/logo-128x128.png") %>" alt="UDIA"> <!-- no SVG support -->
            </object>
          </a>
          <nav role="navigation">
            <ul>
              <%= if @current_user do %>
                <li><%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home) %></li>
              <% end %>
              <%= render "_user_menu.html", assigns %>
            </ul>
          </nav>
        </section>
      </header>
      <%= @inner_content %>
      <footer>
        <%= link "ThreeJS Example Demo Worlds", to: Routes.three_js_path(@conn, :index) %>
        <hr/>
        <%= link "UDIA", to: Routes.home_path(@conn, :index) %>
      </footer>
    </div>
  </body>
</html>